name: my_spotify
services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    container_name: your_spotify
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://192.168.178.69:8008
      - SPOTIFY_SECRET=${SPOTIFY_SECRET_API_KEY}
      - SPOTIFY_PUBLIC= ${SPOTIFY_PUBLIC_API_KEY}
      - CORS=http://192.168.178.69:8008
      - MONGO_ENDPOINT=mongodb://192.168.178.69:27017/your_spotify
    ports:
      - 8008:80
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: