name: free-https-letsencrypt
services:
  swag:
    image: linuxserver/letsencrypt
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - URL=192.168.178.69
      - SUBDOMAINS=www,
      - VALIDATION=https
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - letsencrypt-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

volumes:
  letsencrypt-config: